# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200630_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Life', max_length=50),
        ),
    ]
